/**
 * Transcripts API - List and Create
 *
 * GET  /api/transcripts         - List all transcripts (paginated)
 * POST /api/transcripts         - Save/upsert a transcript
 */

export async function onRequestGet(context) {
    const { env, request } = context;
    const url = new URL(request.url);

    const limit = parseInt(url.searchParams.get('limit') || '50');
    const offset = parseInt(url.searchParams.get('offset') || '0');

    try {
        const result = await env.DB.prepare(`
            SELECT id, video_id, title, channel_name, captured_at,
                   language, is_auto_generated, word_count
            FROM transcripts
            ORDER BY captured_at DESC
            LIMIT ? OFFSET ?
        `).bind(limit, offset).all();

        return jsonResponse({ transcripts: result.results });
    } catch (err) {
        return jsonResponse({ error: err.message }, 500);
    }
}

export async function onRequestPost(context) {
    const { env, request } = context;

    try {
        const data = await request.json();

        // Convert undefined to null for D1 compatibility
        const videoId = data.videoId;
        const title = data.title ?? null;
        const channelName = data.channelName ?? null;
        const videoUrl = data.videoUrl ?? null;
        const durationSeconds = data.durationSeconds ?? null;
        const publishDate = data.publishDate ?? null;
        const rawJson = data.rawJson ?? null;
        const cleanText = data.cleanText ?? null;
        const language = data.language ?? null;
        const isAutoGenerated = data.isAutoGenerated ? 1 : 0;
        const wordCount = data.wordCount ?? null;

        if (!videoId) {
            return jsonResponse({ error: 'videoId is required' }, 400);
        }

        // Check if exists
        const existing = await env.DB.prepare(
            `SELECT id FROM transcripts WHERE video_id = ?`
        ).bind(videoId).first();

        if (existing) {
            // Update
            await env.DB.prepare(`
                UPDATE transcripts SET
                    title = ?, channel_name = ?, video_url = ?, duration_seconds = ?,
                    publish_date = ?, raw_json = ?, clean_text = ?, language = ?,
                    is_auto_generated = ?, word_count = ?, captured_at = datetime('now')
                WHERE video_id = ?
            `).bind(
                title, channelName, videoUrl, durationSeconds, publishDate,
                rawJson, cleanText, language, isAutoGenerated, wordCount, videoId
            ).run();
        } else {
            // Insert
            await env.DB.prepare(`
                INSERT INTO transcripts
                (video_id, title, channel_name, video_url, duration_seconds, publish_date,
                 raw_json, clean_text, language, is_auto_generated, word_count)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            `).bind(
                videoId, title, channelName, videoUrl, durationSeconds, publishDate,
                rawJson, cleanText, language, isAutoGenerated, wordCount
            ).run();
        }

        return jsonResponse({ saved: true, videoId });
    } catch (err) {
        return jsonResponse({ error: err.message }, 500);
    }
}

function jsonResponse(data, status = 200) {
    return new Response(JSON.stringify(data), {
        status,
        headers: { 'Content-Type': 'application/json' }
    });
}
